MyHospital/Models/Service.cs
using System.ComponentModel.DataAnnotations;

namespace MyHospital.Models
{
    public class Service
    {
        [Key]
        public int Id { get; set; }
        public string Uid { get; set; } = Guid.NewGuid().ToString();
        public string Name { get; set; }
    }
}

MyHospital/Controllers/ServicesController.cs
using majed_asp_mvc.Filters;
using Microsoft.AspNetCore.Mvc;
using MyHospital.Data;
using MyHospital.Interfaces;
using MyHospital.Models;

namespace MyHospital.Controllers
{
    [SessionAuthorize]
    public class ServicesController : Controller
    {

        //private readonly ApplicationDbContext _context;
        //public ServicesController(ApplicationDbContext context)
        //{
        //    _context = context;
        //}

        private readonly IRepository<Service> _repositoryService;
        public ServicesController(IRepository<Service> repositoryService)
        {
            _repositoryService = repositoryService;
        }


        //-----------------------------

        public IActionResult Index()
        {
            try
            {
                //IEnumerable<Service> services = _context.Services.ToList();
                IEnumerable<Service> services = _repositoryService.GetAll();


                ////تحديث Uid 
                //foreach (var item in services)
                //{
                //    item.Uid = Guid.NewGuid().ToString();
                //    _context.Services.Update(item);
                //    _context.SaveChanges();
                //}


                return View(services);
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }

        //-----------------------------


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Service service)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(service);
                }

                //_context.Services.Add(service);
                //_context.SaveChanges();

                _repositoryService.Add(service);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }

        [HttpGet]
        public IActionResult Edit(string Uid)
        {
            //var service = _context.Services.Find(Id);
            //var service = _context.Services.FirstOrDefault(e => e.Uid == Uid);
            var service = _repositoryService.GetByUId(Uid);
            return View(service);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Service service, string Uid)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(service);
                }

                //var s = _context.Services.FirstOrDefault(e => e.Uid == Uid);
                var s = _repositoryService.GetByUId(Uid);
                if (s != null)
                {
                    s.Name = service.Name;

                    //_context.Services.Update(s);
                    //_context.SaveChanges();

                    _repositoryService.Update(s);
                    return RedirectToAction("Index");
                }
                return View(service);
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }


        [HttpGet]
        public IActionResult Delete(string Uid)
        {
            //var service = _context.Services.Find(Id);
            //var service = _context.Services.FirstOrDefault(e => e.Uid == Uid);
            var service = _repositoryService.GetByUId(Uid);
            return View(service);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Service service)
        {
            try
            {
                //var item = _context.Services.FirstOrDefault(e => e.Uid == service.Uid);
                var item = _repositoryService.GetByUId(service.Uid);
                if (item != null)
                {
                    //_context.Services.Remove(item);
                    //_context.SaveChanges();

                    _repositoryService.Delete(item.Uid);

                    return RedirectToAction("Index");
                }
                return View(service);
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }















    }
}

MyHospital/Views/Services/Create.cshtml
@model Service
@{
    ViewData["Title"] = "Create";
}

<h1>Add Service</h1>

<form method="post" asp-action="Create">
    @Html.AntiForgeryToken()

    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" name="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-outline-primary">Save</button>
    <a asp-action="Index" class="btn btn-dark">Back</a>

</form>

MyHospital/Views/Services/Delete.cshtml
@model Service
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Service</h1>

<form method="post" asp-action="Delete">
    @Html.AntiForgeryToken()

    <input asp-for="Uid" type="hidden" name="Uid" class="form-control" />

    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" disabled name="Name" class="form-control" />
    </div>

    <button type="submit" class="btn btn-outline-danger">Delete</button>
    <a asp-action="Index" class="btn btn-dark">Back</a>

</form>

MyHospital/Views/Services/Edit.cshtml
@model Service
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Service</h1>

<form method="post" asp-action="Edit">
    @Html.AntiForgeryToken()

    <input asp-for="Uid" type="hidden" name="Uid" class="form-control" />

    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" name="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-outline-primary">Update</button>
    <a asp-action="Index" class="btn btn-dark">Back</a>

</form>

MyHospital/Views/Services/Index.cshtml
@model IEnumerable<Service>
@{
    ViewData["Title"] = "Manage Service";
}

<h1>Manage Service || Add Edit Delete</h1>

<div class="container">

    <div class="text-end">

        <a asp-controller="Services" asp-action="Create" class="btn btn-outline-primary">Add New</a>

    </div>


    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var service in Model)
            {

                <tr>
                    <td>@service.Id</td>
                    <td>@service.Name</td>
                    <td>
                        <a asp-action="Edit" asp-route-Uid="@service.Uid" class="btn btn-outline-warning">Edit</a>
                        <a asp-action="Delete" asp-route-Uid="@service.Uid" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

            }


        </tbody>
    </table>
</div>