MyHospital/Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace MyHospital.Models
{
    public class Department
    {
        [Key]
        public int Id { get; set; }
        public string Uid { get; set; } = Guid.NewGuid().ToString();
        public string Name { get; set; }

        public ICollection<Employee>? Employees { get; set; }

    }


}

MyHospital/Controllers/DepartmentsController.cs
using majed_asp_mvc.Filters;
using Microsoft.AspNetCore.Mvc;
using MyHospital.Data;
using MyHospital.Interfaces;
using MyHospital.Models;

namespace MyHospital.Controllers
{
    [SessionAuthorize]

    public class DepartmentsController : Controller
    {

        //private readonly ApplicationDbContext _context;
        //public DepartmentsController(ApplicationDbContext context)
        //{
        //    _context = context;
        //}

        private readonly IRepository<Department> _repositoryDepartment;

        public DepartmentsController(IRepository<Department> repositoryDepartment)
        {
            _repositoryDepartment = repositoryDepartment;
        }


        //----------------------------------------------------


        public IActionResult Index()
        {
            try
            {
                //IEnumerable<Department> depts = _context.Departments.ToList();
                IEnumerable<Department> depts = _repositoryDepartment.GetAll();

                ////تحديث Uid 
                //foreach (var item in depts)
                //{
                //    item.Uid = Guid.NewGuid().ToString();

                //    _context.Departments.Update(item);
                //    _context.SaveChanges();
                //}

                return View(depts);
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }


        //---------------------------


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Department dept)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(dept);
                }

                //_context.Departments.Add(dept);
                //_context.SaveChanges();

                _repositoryDepartment.Add(dept);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }

        [HttpGet]
        public IActionResult Edit(string Uid)
        {
            //var dept = _context.Departments.Find(Id);
            //var dept = _context.Departments.FirstOrDefault(e => e.Uid == Uid);
            var dept = _repositoryDepartment.GetByUId(Uid);
            return View(dept);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Department dept, string Uid)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(dept);
                }

                //var department = _context.Departments.FirstOrDefault(e => e.Uid == Uid);
                var department = _repositoryDepartment.GetByUId(Uid);
                if (department != null)
                {
                    department.Name = dept.Name;
                    //_context.Departments.Update(department);
                    //_context.SaveChanges();

                    _repositoryDepartment.Update(department);
                    return RedirectToAction("Index");
                }
                return View(dept);

            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }


        [HttpGet]
        public IActionResult Delete(string Uid)
        {
            //var dept = _context.Departments.Find(Id);
            //var dept = _context.Departments.FirstOrDefault(e => e.Uid == Uid);
            var dept = _repositoryDepartment.GetByUId(Uid);
            return View(dept);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Department dept, string Uid)
        {
            try
            {
                //var department = _context.Departments.FirstOrDefault(e => e.Uid == dept.Uid);
                var department = _repositoryDepartment.GetByUId(Uid);
                if (department != null) 
                {
                    //_context.Departments.Remove(department);
                    //_context.SaveChanges();

                    _repositoryDepartment.Delete(dept.Uid);
                    return RedirectToAction("Index");
                }
                return View(dept);


            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }










    }
}

MyHospital/Views/Departments/Create.cshtml
@model Department
@{
    ViewData["Title"] = "Create";
}

<h1>Add Department</h1>

<form method="post" asp-action="Create">
    @Html.AntiForgeryToken()

    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" name="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-outline-primary">Save</button>
    <a asp-action="Index" class="btn btn-dark">Back</a>

</form>

MyHospital/Views/Departments/Delete.cshtml
@model Department
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Department</h1>

<form method="post" asp-action="Delete">
    @Html.AntiForgeryToken()

    <input asp-for="Uid" type="hidden" name="Uid" class="form-control" />

    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" disabled name="Name" class="form-control" />
    </div>

    <button type="submit" class="btn btn-outline-danger">Delete</button>
    <a asp-action="Index" class="btn btn-dark">Back</a>

</form>

MyHospital/Views/Departments/Edit.cshtml
@model Department
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Department</h1>

<form method="post" asp-action="Edit">
    @Html.AntiForgeryToken()

    <input asp-for="Uid" type="hidden" name="Uid" class="form-control" />

    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" name="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-outline-primary">Update</button>
    <a asp-action="Index" class="btn btn-dark">Back</a>

</form>

MyHospital/Views/Departments/Index.cshtml
@model IEnumerable<Department>
@{
    ViewData["Title"] = "Index";
}

<h1>Department</h1>

<div class="container-fluid">

    <div class="text-end mb-3">

        <a asp-controller="Departments" asp-action="Create" class="btn btn-outline-primary">Add New</a>

    </div>


    <div class="table-responsive">
        <table class="table table-striped table-hover">

            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var dept in Model)
                {

                    <tr>
                        <td>@dept.Id</td>
                        <td>@dept.Name</td>
                        <td>
                            <a asp-action="Edit" asp-route-Uid="@dept.Uid" class="btn btn-outline-warning">Edit</a>
                            <a asp-action="Delete" asp-route-Uid="@dept.Uid" class="btn btn-outline-danger">Delete</a>
                        </td>
                    </tr>

                }


            </tbody>
        </table>

    </div>
</div>