MyHospital/Models/FAQ.cs
using System.ComponentModel.DataAnnotations;

namespace MyHospital.Models
{
    public class Faq
    {
        [Key]
        public int Id { get; set; }
        public string Uid { get; set; } = Guid.NewGuid().ToString();
        public string Question { get; set; }
        public string Answer { get; set; }
    }
}

MyHospital/Controllers/FAQController.cs
using majed_asp_mvc.Filters;
using Microsoft.AspNetCore.Mvc;
using MyHospital.Data;
using MyHospital.Models;

namespace MyHospital.Controllers
{
    [SessionAuthorize]
    public class FAQController : Controller
    {

        private readonly ApplicationDbContext _context;
        public FAQController(ApplicationDbContext context)
        {
            _context = context;
        }

        //----------------------------------------------------



        public IActionResult Index()
        {
            try
            {
                IEnumerable<FAQ> faq = _context.FAQs.ToList();
                return View(faq);
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }


        //---------------------------


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(FAQ faq)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(faq);
                }

                _context.FAQs.Add(faq);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var faq = _context.FAQs.Find(Id);
            return View(faq);
        }

        [HttpPost]
        public IActionResult Edit(FAQ faq)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(faq);
                }

                _context.FAQs.Update(faq);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }


        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var faq = _context.FAQs.Find(Id);
            return View(faq);
        }

        [HttpPost]
        public IActionResult Delete(FAQ faq)
        {
            try
            {
                _context.FAQs.Remove(faq);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }












    }
}

MyHospital/Controllers/FaqsController.cs
using majed_asp_mvc.Filters;
using Microsoft.AspNetCore.Mvc;
using MyHospital.Data;
using MyHospital.Interfaces;
using MyHospital.Models;

namespace MyHospital.Controllers
{
    [SessionAuthorize]
    public class FaqsController : Controller
    {

        //private readonly ApplicationDbContext _context;
        //public FaqsController(ApplicationDbContext context)
        //{
        //    _context = context;
        //}

        private readonly IRepository<Faq> _repositoryFaq;
        public FaqsController(IRepository<Faq> repositoryFaq)
        {
            _repositoryFaq = repositoryFaq;
        }

        //----------------------------------------------------



        public IActionResult Index()
        {
            try
            {
                //IEnumerable<Faq> faq = _context.Faqs.ToList();
                IEnumerable<Faq> faq = _repositoryFaq.GetAll();

                //تحديث Uid 
                //foreach (var item in faq)
                //{
                //    item.Uid = Guid.NewGuid().ToString();

                //    _context.Faqs.Update(item);
                //    _context.SaveChanges();
                //}

                return View(faq);
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }


        //---------------------------


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Faq faq)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(faq);
                }

                //_context.Faqs.Add(faq);
                //_context.SaveChanges();

                _repositoryFaq.Add(faq);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }

        [HttpGet]
        public IActionResult Edit(string Uid)
        {
            //var faq = _context.Faqs.Find(Id);
            //var faq = _context.Faqs.FirstOrDefault(e => e.Uid == Uid);
            var faq = _repositoryFaq.GetByUId(Uid);
            return View(faq);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Faq faq, string Uid)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(faq);
                }

                //var f = _context.Faqs.FirstOrDefault(e => e.Uid == Uid);
                var f = _repositoryFaq.GetByUId(Uid);
                if (f != null)
                {
                    f.Question = faq.Question;
                    f.Answer = faq.Answer;

                    //_context.Faqs.Update(f);
                    //_context.SaveChanges();

                    _repositoryFaq.Update(f);
                    return RedirectToAction("Index");
                }
                return View(faq);
                
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }


        [HttpGet]
        public IActionResult Delete(string Uid)
        {
            //var faq = _context.Faqs.Find(Id);
            //var faq = _context.Faqs.FirstOrDefault(e => e.Uid == Uid);
            var faq = _repositoryFaq.GetByUId(Uid);
            return View(faq);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Faq faq)
        {
            try
            {
                //var item = _context.Faqs.FirstOrDefault(e => e.Uid == faq.Uid);
                var item = _repositoryFaq.GetByUId(faq.Uid);
                if (item != null)
                {
                    //_context.Faqs.Remove(item);
                    //_context.SaveChanges();

                    _repositoryFaq.Delete(item.Uid);
                    return RedirectToAction("Index");
                }
                return View(faq);
            }
            catch (Exception ex)
            {
                return Content("حدث خطا غير متوقع يرجي مراجهة الدعم الفني:0565455252545");
            }
        }












    }
}

MyHospital/Views/Faqs/Create.cshtml
@model Faq
@{
    ViewData["Title"] = "Create";
}

<h1>Add Faq</h1>

<form method="post" asp-action="Create">
    @Html.AntiForgeryToken()

    <div class="mb-3">
        <label asp-for="Question" class="form-label"></label>
        <input asp-for="Question" name="Question" class="form-control" />
        <span asp-validation-for="Question" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Answer" class="form-label"></label>
        <textarea asp-for="Answer" name="Answer" class="form-control"></textarea>

    </div>

    <button type="submit" class="btn btn-outline-primary">Save</button>
    <a asp-action="Index" class="btn btn-dark">Back</a>

</form>

MyHospital/Views/Faqs/Delete.cshtml
@model Faq
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Faq</h1>

<form method="post" asp-action="Delete">
    @Html.AntiForgeryToken()

    <input asp-for="Uid" type="hidden" name="Uid" class="form-control" />

    <div class="mb-3">
        <label asp-for="Question" class="form-label"></label>
        <input asp-for="Question" disabled name="Question" class="form-control" />

    </div>
    <div class="mb-3">
        <label asp-for="Answer" class="form-label"></label>
        <textarea asp-for="Answer" disabled name="Answer" class="form-control"></textarea>

    </div>

    <button type="submit" class="btn btn-outline-danger">Delete</button>
    <a asp-action="Index" class="btn btn-dark">Back</a>

</form>

MyHospital/Views/Faqs/Edit.cshtml
@model Faq
@{
    ViewData["Title"] = "Edit";
}

<h1>Add Faq</h1>

<form method="post" asp-action="Edit">
    @Html.AntiForgeryToken()

    <input asp-for="Uid" type="hidden" name="Uid" class="form-control" />

    <div class="mb-3">
        <label asp-for="Question" class="form-label"></label>
        <input asp-for="Question" name="Question" class="form-control" />
        <span asp-validation-for="Question" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Answer" class="form-label"></label>
        <textarea asp-for="Answer" name="Answer" class="form-control"></textarea>

    </div>

    <button type="submit" class="btn btn-outline-primary">Update</button>
    <a asp-action="Index" class="btn btn-dark">Back</a>

</form>

MyHospital/Views/Faqs/Index.cshtml
@model IEnumerable<Faq>
@{
    ViewData["Title"] = "Manage Faqs";
}

<h1>Manage Faqs || Add Edit Delete</h1>

<div class="container">

    <div class="text-end">

        <a asp-controller="Faqs" asp-action="Create" class="btn btn-outline-primary">Add New</a>

    </div>


    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Question</th>
                <th>Answer</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var faq in Model)
            {

                <tr>
                    <td>@faq.Id</td>
                    <td>@faq.Question</td>
                    <td>@faq.Answer</td>
                    <td>
                        <a asp-action="Edit" asp-route-Uid="@faq.Uid" class="btn btn-outline-warning">Edit</a>
                        <a asp-action="Delete" asp-route-Uid="@faq.Uid" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

            }


        </tbody>
    </table>
</div>